### ISSUE TITLE
Upgrade the OnPropertyChanged?

### ISSUE THREAD

**Issue by vhugogarcia** [davidezordan/UsingValidation#3]
Hello @davidezordan 

I would like to thank you for this amazing shared code, it worked fantastic, however, I'm getting a warning on the ValidationBase.cs file saying that BindableBase.OnPropertyChanged() is obsolete and that is planned to be removed in the future.

<img width="881" alt="screen shot 2018-03-15 at 10 38 04 am" src="https://user-images.githubusercontent.com/1047398/37477392-36ba7be4-283d-11e8-86b1-d4ae8da90fb8.png">

do you know how to upgrade it? I gave it a try without luck.

Thanks in advance

**Comment by vhugogarcia** [comment]
I spoke too fast. I was able to update it by just:

RaisePropertyChanged("HasErrors");
RaisePropertyChanged("ErrorsList");

I was doing it wrong.

Thanks again

**Comment by davidezordan** [comment]
Thank you @vhugogarcia. Feel free to send a PR if you like, otherwise I will get this fixed in the next days.

**Comment by vhugogarcia** [comment]
I will for sure! Thanks @davidezordan just let me finish it to update it, I'm trying to display the error message below each entry instead of all of them under a list view.

I'm trying to do it by adding a children programmatically to the entry, but it seems not to be possible

_associatedObject_TextChanged event.

Do you have an idea?

**Comment by vhugogarcia** [comment]
I figured out. By adding the XAML Label:
<Label Text="{Binding DemoItem.ErrorsList, Converter={StaticResource FirstValidationErrorConverter}}" Style="{StaticResource ErrorLabelStyle}"></Label>

However, my last step is now to configure it to trigger the validation after first character is typed or on button click due to right now the error validation is being shown since the load of the screen.

do you have an idea where to go and edit that @davidezordan ?

**Comment by vhugogarcia** [comment]
ok, I tried already to modify it to accomplish the goal of showing the error message below each entry without success.

I need to re-think this different I guess

**Comment by vhugogarcia** [comment]
oh! I found a way by going to the Parent Element, we just need to make sure to wrap each entry on a StackLayout

`void _associatedObject_TextChanged(object sender, TextChangedEventArgs e)
        {
            var source = _associatedObject.BindingContext as ValidationBase;
            if (source != null && !string.IsNullOrEmpty(PropertyName))
            {
                var errors = source.GetErrors(PropertyName).Cast<string>();
                if (errors != null && errors.Any())
                {
                    flag = true;
                    var borderEffect = _associatedObject.Effects.FirstOrDefault(eff => eff is BorderEffect);
                    if (borderEffect == null)
                    {
                        _associatedObject.Effects.Add(new BorderEffect());

                    }

                    if (Device.RuntimePlatform != Device.WinRT)
                    {
                        
                        var associatedLayout = _associatedObject.Parent as StackLayout;
                        if (associatedLayout != null)
                        {
                            Label errorMessageLabel = new Label
                            {
                                Text = errors.ElementAt(0),
                                HorizontalOptions = LayoutOptions.StartAndExpand,
                                Style = (Style)Application.Current.Resources["ErrorLabelStyle"]
                            };

                            // BEfore add the label let's remove the old one
                            if (associatedLayout.Children.Count > 1)
                                associatedLayout.Children.RemoveAt(1);

                            associatedLayout.Children.Add(errorMessageLabel);
                        }

                        _associatedObject.BackgroundColor = Color.FromHex("#FFEBEE");
                    }
                }
                else
                {
                    var borderEffect = _associatedObject.Effects.FirstOrDefault(eff => eff is BorderEffect);
                    if (borderEffect != null)
                    {
                        _associatedObject.Effects.Remove(borderEffect);
                    }

                    if (Device.RuntimePlatform != Device.WinRT)
                    {
                        var associatedLayout = _associatedObject.Parent as StackLayout;
                        if (associatedLayout.Children.Count > 1)
                            associatedLayout.Children.RemoveAt(1);
                        
                        _associatedObject.BackgroundColor = Color.Default;
                    }
                }


            }
        }`

It is still unknown how to avoid the entry effects too be applied on Screen/Page load, I rather prefer them to be applied once they start typing.

Any idea?

**Comment by davidezordan** [comment]
A simple solution would be to put a flag for skipping the _associatedObject_TextChanged on load:
Something like:

```
using System.Linq;
using UsingValidation.Effects;
using Xamarin.Forms;

namespace UsingValidation.Validation
{
    public class EntryValidationBehavior : Behavior<Entry>
    {
        bool _init = false;

	private Entry _associatedObject;

        protected override void OnAttachedTo(Entry bindable)
        {
            base.OnAttachedTo(bindable);
            // Perform setup       

            _associatedObject = bindable;

		_associatedObject.TextChanged += _associatedObject_TextChanged;
        }

	void _associatedObject_TextChanged(object sender, TextChangedEventArgs e)
	{
            if (!_init)
            {
                _init = true;
                return;
            }

```

**Comment by vhugogarcia** [comment]
That worked! thanks @davidezordan 

Btw, one off-topic question: Is this approach not following an MVVM pattern in real? just curiosity, I heard some comments out there about it.

**Comment by davidezordan** [comment]
You're welcome. In my opinion MVVM is enforced as we are separating the UI effects using XAML Behaviors from the validation logic.
